version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: duck
      POSTGRES_PASSWORD: duck
      POSTGRES_DATABASE: duck
    ports:
      - 5432:5432
